// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUAHzJuc3-lNF9jHy7__VEdTMNJ4X894s',
    appId: '1:611133957942:web:e801fc6eb75d649207b597',
    messagingSenderId: '611133957942',
    projectId: 'nemras-3230f',
    authDomain: 'nemras-3230f.firebaseapp.com',
    storageBucket: 'nemras-3230f.firebasestorage.app',
    measurementId: 'G-MCY4WD71BR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGD0B589MFYPyD-IpA8NIEbV2KO3oZsFk',
    appId: '1:611133957942:android:3ac994687a9e597907b597',
    messagingSenderId: '611133957942',
    projectId: 'nemras-3230f',
    storageBucket: 'nemras-3230f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx-5Qekxtg6GFwGRXb0WTkj80g2uFlkRA',
    appId: '1:611133957942:ios:dc489eac9936ec1a07b597',
    messagingSenderId: '611133957942',
    projectId: 'nemras-3230f',
    storageBucket: 'nemras-3230f.firebasestorage.app',
    iosBundleId: 'com.example.nemras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx-5Qekxtg6GFwGRXb0WTkj80g2uFlkRA',
    appId: '1:611133957942:ios:dc489eac9936ec1a07b597',
    messagingSenderId: '611133957942',
    projectId: 'nemras-3230f',
    storageBucket: 'nemras-3230f.firebasestorage.app',
    iosBundleId: 'com.example.nemras',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUAHzJuc3-lNF9jHy7__VEdTMNJ4X894s',
    appId: '1:611133957942:web:73138b34cbb2d72b07b597',
    messagingSenderId: '611133957942',
    projectId: 'nemras-3230f',
    authDomain: 'nemras-3230f.firebaseapp.com',
    storageBucket: 'nemras-3230f.firebasestorage.app',
    measurementId: 'G-3WSR2Q5XCY',
  );
}
